### ISSUE TITLE
Is autocomplete for Python supported?

### ISSUE THREAD

**Issue by dclong** [bitnami/bitnami-docker-codiad#13]
Is autocomplete for Python supported in Codiad?

**Comment by carrodher** [comment]
Hi, for information regarding the application itself or customization of the content within the application, we highly recommend checking forums and user guides made available by the project behind the application. Checking the [Codiad](http://codiad.com/) site, they include "Smart auto-complete" as a Codiad feature. On the same way, checking the [Plugins](http://market.codiad.com/) section appears the following plugin:

 - [CompletePlus](https://github.com/Andr3as/Codiad-CompletePlus) (Alternative autocomplete; Expandable by plugins)

But surely, by asking this question in the [Codiad repository](https://github.com/Codiad/Codiad) you will get more information.
