### ISSUE TITLE
Example Caddyfile for reverse proxy?

### ISSUE THREAD

**Issue by mitchellurgero** [bitnami/bitnami-docker-codiad#14]
As the name implies, just have issues getting reverse proxy to work, container reports 404 not found when I use a reverse proxy for this container.

Anyone have a working caddyfile for this?

**Comment by beltran-rubo** [comment]
Could you post the config file you are using? Are you using Caddy as a container too? This application does not have any specific requirement for domains or IPs so it does not require any specific rule for working behind a reverse proxy.

**Comment by mitchellurgero** [comment]
Current config:

```
domain.tld {
    proxy /codiad http://localhost:8080 {
        transparent
    }
}
```

**Comment by beltran-rubo** [comment]
Correct, the issue is you are using a sub-folder for the redirection. I would suggest to use a VirtualHost for that, that would be the easiest option. I hope it helps.

**Comment by mitchellurgero** [comment]
There is no redirection. It is a reverse proxy, that being said I cannot use a whole domain just for codiad as I want to make this super hidden Doing the same reverse proxy in nginx works as expect on the sub folder. so we can close this.


Thanks!
